### ISSUE TITLE
Temporarily exiting the app with the back key causes it to crash the next time it is opened.

### ISSUE THREAD

**Issue by codaphrenic** [federicoiosue/Omni-Notes#454] opened 2018-03-23 14:50 UTC
#### Expected behavior
I expect to temporarily exit the app using the designated android **back key** with no hassles. Such that when I re-open the tab, I should gain access to the app's dashboard and open menus where I left off.

#### Actual behavior
On exiting the app with the back key, I am unable to continue from the homepage or where I left off. Instead, it crashes and runs into an error when I open it. 

However,  the case is different when I exit the app with the **home** key or the **recent tabs** key. 

#### How to reproduce
* download the app from fdroid store
* launch app and allow permissions if prompted
* On the homepage, exit the app with the back button 
* Now go back to opening the app from either the minimized tabs or by clicking directly on it from its icon on your phone menu.  
* You'll notice a blank white screen, and at the top right corner is a *Go Back* arrow labeled **Omni Notes Floss**. The app crashes when you click this arrow.

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Omni Notes FOSS
* version: 5.4.4

#### Recording Of The Bug

<center>
https://youtu.be/g5QKq-SbyVM
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/temporarily-exiting-the-app-with-the-back-key-causes-it-to-crash-the-next-time-it-is-opened">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Apokalypzx** [comment] 2018-03-24 20:24
I can confirm the same issue here:

Exiting app from back button and reloading app from app drawer causes app to reload with just Omni Notes FOSS titlebar and back arrow on top left. Pressing that back arrow opens the side panel which contains just the Omni Notes FOSS title and settings option and immediately crashes with a force close dialog.

I find this is the only way to reproduce the issue. Leaving the app from the home button or app switcher and reloading the app from the app drawer or app switcher does not cause the issue.

Details:
Android 8.1 (Lineage OS unofficial build)
Device: Pixel XL
App version: 5.4.4
Installed from f-droid
App has access to all requested permissions.

**Comment by federicoiosue** [comment] 2018-03-24 22:49
Duplicate of #444

**Closed by federicoiosue** 2018-03-24 22:49 UTC
