### ISSUE TITLE
Cloud saving

### ISSUE THREAD

**Issue by jaimejimbo** [federicoiosue/Omni-Notes#185] opened 2015-07-10 20:23 UTC
It would be great to use some cloud file system to save notes. I mean, like having a git on dropbox that saves all changes and allow to go backwards. I have lost my notes twice because an error of my terminal.

**Comment by jaimejimbo** [comment] 2015-07-10 20:24
I know that there is an option to backup the notes, but I mean that it could be automatic when closing a note(for example) and do it in the dropbox/drive folder.

**Comment by federicoiosue** [comment] 2015-07-15 11:56
Duplicate of https://github.com/federicoiosue/Omni-Notes/issues/55

**Closed by federicoiosue** 2015-07-15 11:56 UTC
Labels: duplicate
