### ISSUE TITLE
unable to run on android

### ISSUE THREAD

**Issue by kapparition** [federicoiosue/Omni-Notes#676] opened 2019-05-07 07:46 UTC
hello,
i am unable to run it on android studio in w10 os
please tell me what to do facing with 

omniNotes:transformDexArchiveWithExternalLibsDexMergerForAlphaDebug

error.
Pleae help new to this

**Comment by federicoiosue** [comment] 2019-06-07 17:14
Just a partial success

**Comment by federicoiosue** [comment] 2019-10-14 12:09
Duplicate of #669

**Closed by federicoiosue** 2019-10-14 12:09 UTC
Labels: Development
