### ISSUE TITLE
can't get rid of deleted note with reminder

### ISSUE THREAD

**Issue by alekksander** [federicoiosue/Omni-Notes#370] opened 2017-05-25 16:21 UTC
create note —> add daily reminder —> let it ring as desired —> move to trash (when after few days or so it's no longer needed) —> delete from there permanently… —> next day —> say hello to your permanently removed note with reminder, it's back because it loves you! (or it's bugged, and shouldn't remind you stuff from the past)

**Comment by federicoiosue** [comment] 2017-06-05 19:59
Duplicate of #374

**Closed by federicoiosue** 2017-06-05 19:59 UTC
Labels: duplicate
