### ISSUE TITLE
Feature Request - Fingerprint lock

### ISSUE THREAD

**Issue by doctor-owl** [federicoiosue/Omni-Notes#665] opened 2019-03-09 01:47 UTC
I looked to see if this has been requested already and didn't see it, so I apologise if I missed it.

I love that we can use password protection, but tbh since I use this as my main note taking app (switched over from Writer Plus!) I find entering a full password a bit clunky. Someone else has requested pin lock, but I think fingerprint lock would be even better. I've begun using fingerprint lock for every app that allows it, and it's soooo much more fluid and "one-handed friendly."

Maybe I'm just lazy and don't want to use two hands, but hopefully I'm not alone :P I'd be very grateful if this was implemented in the future!

**Comment by federicoiosue** [comment] 2019-10-04 21:59
Duplicate of #275

**Closed by federicoiosue** 2019-10-04 21:59 UTC
