### ISSUE TITLE
delete action cause crash in checklist

### ISSUE THREAD

**Issue by flashlab** [federicoiosue/Omni-Notes#143] opened 2015-04-14 09:30 UTC
While on the checklist edit screen, I keep press the delete button(in order to delete all the text in current checklist). Once the cursor reach the last letter, crashing is triggered.

**Comment by flashlab** [comment] 2015-04-14 16:15
the nightmare is not end....

when I finish a note and back to the note list, there is a great chance that the float button didn't close. Even though, this is not the worst...

Once the crash happened as described, interface language reset and can't be change any more, also, I can't insert image into notes. 

After I backup data and reinstall ON, click restore, nothing happened. Until I manually move the db file and xml file to /data/data..  then, the whole application just mess up. I really don't know how to recover it, please help....

**Comment by flashlab** [comment] 2015-04-14 16:40
sorry, Forget to mention I was using android 4.4.2 and beta17 download from google drive. No matter how many times I reinstalled, once the app reopened(killed or reboot phone) after the first run, both language problem and attach problem arised. Thanks

**Comment by federicoiosue** [comment] 2015-04-14 22:23
**4.4.2** and beta17 ?

**Comment by federicoiosue** [comment] 2015-04-14 22:26
Did you sent (the app should do it automatically if you've data on) a crasj report?

Could you tell me your device model?

**Comment by flashlab** [comment] 2015-04-15 02:22
Yes, it should have send reports. Here is the model
NX503A_Z0_CN_ASPPL1DD11H212

3.4.0-perf-g4008ce7
nubia@swlab-1t049 #1
Sat Oct 11 18:51:56 CST 2014

**Comment by flashlab** [comment] 2015-04-15 15:50
Hi~ think I've fix the two problem partly! 
First ,the language problem. after I erase all data in the setting,  
zh-cn comes back, then change lang into zh-tw, import database, click message toolbar to restart ON, the zh-tw hold! at last, turn lang into zh-cn, everything is ok when I restart ON. Though I don't know why, but it works.
Second, the file import failure problem may cause by the changelog dialog. Everytime ON start( OR restart after data restore OR change lang ), the changelog will refresh, and because of my poor cell phone signal, it takes a long time.(see the screenshot) Before the content loaded, attach file operation won't work.

Third, I can't choose attach though Mixplorer, no matter one or multi files were selected, it tells me "error saving attachments". I hope selecting mutifiles will be considered in the future.

At last, foregive  for my poor english and thanks for your pacient.


[img_20150415_232232](https://cloud.githubusercontent.com/assets/4102853/7162314/766133e6-e3c6-11e4-9254-60f3ccae3d06.JPG)

**Comment by federicoiosue** [comment] 2015-04-25 02:35
So, help me to recap:
1. You select zh-cn but it doesn't stay selected (**resolved**)
2. You try to import notes but notes are not restored. It has nothing no to with changelog dialog on start (that's based on offline data anyway). The only way I have to help you on this is to have some logs
3. Multi file selection is already available and it's based on a specific Intent's flag EXTRA_ALLOW_MULTIPLE, it depends from the third party app you're using the fact that is working or not.

**Comment by Micks29** [comment] 2015-04-25 10:14
1. I can confirm the language bug, I will try to explain well the misbehavior:
When you open app for the first time, language is the same by default on your device, but if you check in Settings > Interface > Language > no language selected in the popup, and it's why the problem happen imo.
For reproduce this bug just install app > open it > close it without any change in settings > open it again and now app still in English even if you try to change this in Settings > Interface > Language because nothing change.
Workaround: when you install app for the first time select the language before close app! If you have already close app, go perform a clear data and then select your language in settings.

This bug still here on beta 20, tested on Galaxy S2 with CM11 KK 4.4.4 and on Galaxy Tab2 with stock Touchwiz Rom JB 4.1.2, I hope that help you for find a fix!

**Comment by federicoiosue** [comment] 2015-04-25 12:41
Fixed thanks.

As a workaround until I'll release the fixed versionn you can perform a backup **without** settings included, clear app data and restore the backup.

**Closed** 2015-04-25 22:32 UTC
