### ISSUE TITLE
Referrals to Google+

### ISSUE THREAD

**Issue by doctor-owl** [federicoiosue/Omni-Notes#702] opened 2019-09-25 20:12 UTC
I'm not sure if this is still being actively developed, but it would be much appreciated if dark mode/theme was implemented. Taking notes late at night just kinda blinds me with the white UI haha. Also the readme still references the Google+ group which no longer exists, might want to update that... Just a suggestion!

**Comment by federicoiosue** [comment] 2019-09-25 23:44
Yes thanks, I removed the screen from app tour referencing G+ (beloved platform) and I'll remove also from readme asap.

For what concerns dark theme there should already be an open issue for that, already associated with "Pro" (paid) version

**Comment by federicoiosue** [comment] 2019-09-25 23:45
Duplicate of #70

**Closed** 2019-10-14 12:07 UTC
Labels: UI/UX
