### ISSUE TITLE
No notes after import/restore

### ISSUE THREAD

**Issue by scus1** [federicoiosue/Omni-Notes#384] opened 2017-07-25 09:12 UTC
I switched phones and wanted to transfer my notes: I created a backup on the old phone, transfered the folder via USB and tried to restore/import the backup on the new phone. There is no error message, however, no notes are show up.

Best regards
scus1

EDIT: I'm on version 5.3.2.

**Comment by federicoiosue** [comment] 2018-03-22 23:13
Duplicate of #380

**Closed by federicoiosue** 2018-03-22 23:13 UTC
Labels: duplicate

**Comment by thiswillbeyourgithub** [comment] 2019-09-25 09:56
This problem still exists. I had to reset my phone and I can't add my hundreds of note. Is there no way to manually fix it ? It is very important for my job

**Comment by federicoiosue** [comment] 2019-09-25 23:41
@thiswillbeyourgithub F-Droid version still has issues fixed on Play Store. The problem about releasing on that platform is that build process is not completely under my control, so some problems aroused and I don't have time correctly to work on them.

**Comment by thiswillbeyourgithub** [comment] 2019-09-26 11:35
Indeed it works on the play store version, thanks for the quick help.

I get an error when trying to decrypt the encrypted note though. Is there a known bug of password not being well imported or is it more likely that I forgot it ? I set up the file the day before losing it :/
